#!/bin/bash

# Update system
sudo yum update -y

# Install dependencies
sudo yum install wget -y
sudo yum install java-17-amazon-corretto-devel -y

# Create app directory
sudo mkdir -p /app && cd /app

# Download Nexus
sudo wget https://download.sonatype.com/nexus/3/nexus-3.79.1-04-linux-x86_64.tar.gz

# Extract and rename
sudo tar -xvf nexus-3.79.1-04-linux-x86_64.tar.gz
sudo mv nexus-3.79.1-04 nexus

# Create nexus user
sudo adduser nexus

# Set permissions
sudo chown -R nexus:nexus /app/nexus
sudo chown -R nexus:nexus /app/sonatype*

# Configure to run as nexus user
sudo sed -i '27i run_as_user="nexus"' /app/nexus/bin/nexus

# Create systemd service
sudo tee /etc/systemd/system/nexus.service > /dev/null << EOL
[Unit]
Description=Nexus Repository Manager
After=network.target

[Service]
Type=forking
LimitNOFILE=65536
User=nexus
Group=nexus
ExecStart=/app/nexus/bin/nexus start
ExecStop=/app/nexus/bin/nexus stop
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOL

# Reload systemd and enable Nexus
sudo systemctl daemon-reload
sudo systemctl enable nexus
sudo systemctl start nexus

# Check status
sudo systemctl status nexus
